/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py AAPL 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py ABBV 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py ABT 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py ADBE 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py AKAM 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py AMD 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py AMT 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py AMZN 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py ATVI 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py BAX 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py BNTX 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py BSX 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py BYND 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py CAG 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py CCI 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py CHGG 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py CHWY 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py CL 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py CLX 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py CMG 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py CNC 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py COR 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py COST 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py COUP 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py CPB 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py CRM 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py CRWD 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py CTXS 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py D 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py DDOG 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py DG 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py DHR 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py DOCU 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py DPZ 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py DXCM 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py EA 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py EBAY 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py EBS 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py EQIX 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py ETSY 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py EVBG 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py GILD 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py GIS 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py GOLD 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py GOOG 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py GSK 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py HD 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py HRL 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py JNJ 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py K 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py KR 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py LLY 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py LOGI 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py LVGO 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py MASI 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py MDLZ 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py MKC 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py MKTX 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py MRNA 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py MRVL 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py MSFT 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py NET 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py NFLX 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py NVDA 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py OKTA 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py PANW 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py PEP 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py PFE 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py PG 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py PLD 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py PRGO 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py PTON 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py PYPL 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py REGN 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py RMD 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py RNG 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py SHOP 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py SJM 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py SNY 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py SPGI 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py SPLK 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py SPOT 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py SQ 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py TDOC 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py TGT 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py TMO 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py TTD 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py TTWO 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py TW 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py TWLO 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py UNH 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py VEEV 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py VZ 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py WING 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py WIX 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py WMT 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py WORK 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py ZM 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py ZS 2018-1-1 terse
/opt/conda/bin/python py-algotrading-ema-crossover-grid-search-batch.py ZTS 2018-1-1 terse
